# Generated by Django 6.0.3 on 2026-04-23 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristDigitalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(db_index=True, max_length=120, unique=True)),
                ('credential_id_hex', models.CharField(max_length=68, unique=True)),
                ('data_hash_hex', models.CharField(max_length=68)),
                ('tx_hash', models.CharField(max_length=68)),
                ('issued_at', models.DateTimeField()),
                ('entry_point', models.CharField(default='app_onboarding', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Digital ID',
                'ordering': ['-created_at'],
            },
        ),
    ]
